import type { SettingCategory } from "@/types/settings-schema";
import DeviceSelector from "@/components/settings/custom/DeviceSelector.vue";
import IconLucidePlay from "~icons/lucide/play";

const playerCategory: SettingCategory = {
  id: "player",
  icon: IconLucidePlay,
  sections: [
    {
      id: "playControl",
      items: [
        {
          key: "autoPlay",
          type: "switch",
          binding: { store: "settings", path: "system.player.autoPlay" },
          defaultValue: true,
        },
        {
          key: "rememberLastTrack",
          type: "switch",
          binding: { store: "settings", path: "system.player.rememberLastTrack" },
          defaultValue: false,
        },
        {
          key: "fadeEnabled",
          type: "switch",
          binding: { store: "settings", path: "system.player.fadeEnabled" },
          defaultValue: true,
          children: [
            {
              key: "fadeDuration",
              type: "slider",
              binding: { store: "settings", path: "system.player.fadeDuration" },
              min: 100,
              max: 600,
              step: 100,
              defaultValue: 200,
              marks: { 100: "100", 200: "200", 600: "600" },
            },
          ],
        },
        {
          key: "loudnessNormalization",
          type: "switch",
          binding: { store: "settings", path: "system.player.loudnessNormalization" },
          defaultValue: false,
          tag: { text: "Beta" },
        },
        {
          key: "songLevel",
          type: "select",
          binding: { store: "settings", path: "player.songLevel" },
          options: [
            { value: "lq", labelKey: "settings.songLevel.lq" },
            { value: "sq", labelKey: "settings.songLevel.sq" },
            { value: "hq", labelKey: "settings.songLevel.hq" },
            { value: "lossless", labelKey: "settings.songLevel.lossless" },
            { value: "hi-res", labelKey: "settings.songLevel.hi-res" },
          ],
          defaultValue: "hq",
        },
      ],
    },
    {
      id: "scrobble",
      tag: { text: "Beta" },
      items: [
        {
          key: "neteaseScrobbleEnabled",
          type: "switch",
          binding: { store: "settings", path: "system.system.neteaseScrobbleEnabled" },
          defaultValue: false,
          children: [
            {
              key: "neteaseScrobbleMode",
              type: "select",
              binding: { store: "settings", path: "system.system.neteaseScrobbleMode" },
              options: [
                { value: "legacy", labelKey: "settings.neteaseScrobbleMode.legacy" },
                { value: "ncbl", labelKey: "settings.neteaseScrobbleMode.ncbl" },
              ],
              defaultValue: "ncbl",
            },
          ],
        },
      ],
    },
    {
      id: "playback",
      items: [
        {
          key: "playerBgType",
          type: "select",
          binding: { store: "settings", path: "player.playerBgType" },
          options: [
            { value: "blur", labelKey: "settings.playerBgType.blur" },
            { value: "solid", labelKey: "settings.playerBgType.solid" },
          ],
          defaultValue: "blur",
        },
        {
          key: "enableFluidBackground",
          type: "switch",
          binding: { store: "settings", path: "player.enableFluidBackground" },
          defaultValue: true,
        },
        {
          key: "enableSnowBackground",
          type: "switch",
          binding: { store: "settings", path: "player.enableSnowBackground" },
          defaultValue: false,
        },
        {
          key: "enableFogBackground",
          type: "switch",
          binding: { store: "settings", path: "player.enableFogBackground" },
          defaultValue: false,
        },
        {
          key: "enableRaindropBackground",
          type: "switch",
          binding: { store: "settings", path: "player.enableRaindropBackground" },
          defaultValue: false,
        },
        {
          key: "coverLayout",
          type: "select",
          binding: { store: "settings", path: "player.coverLayout" },
          options: [
            { value: "default", labelKey: "settings.coverLayout.default" },
            { value: "fullscreen", labelKey: "settings.coverLayout.fullscreen" },
          ],
          defaultValue: "default",
        },
        {
          key: "autoCenterCover",
          type: "switch",
          binding: { store: "settings", path: "player.autoCenterCover" },
          defaultValue: true,
        },
        {
          key: "followCoverColor",
          type: "switch",
          binding: { store: "settings", path: "player.followCoverColor" },
          defaultValue: true,
        },
        {
          key: "autoImmersive",
          type: "switch",
          binding: { store: "settings", path: "player.autoImmersive" },
          defaultValue: false,
        },
        {
          key: "enableParallaxTilt",
          type: "switch",
          binding: { store: "settings", path: "player.enableParallaxTilt" },
          defaultValue: true,
        },
        {
          key: "enableCoverBreathing",
          type: "switch",
          binding: { store: "settings", path: "player.enableCoverBreathing" },
          defaultValue: true,
        },
        {
          key: "enableFanLyrics",
          type: "switch",
          binding: { store: "settings", path: "player.enableFanLyrics" },
          defaultValue: false,
          children: [
            {
              key: "fanLyricsAngle",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsAngle" },
              defaultValue: 60,
              min: -90,
              max: 90,
              step: 1,
              marks: { "-90": "-90", "-30": "-30", 0: "0", 30: "30", 60: "60", 90: "90" },
            },
            {
              key: "fanLyricsMaxLines",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMaxLines" },
              defaultValue: 7,
              min: 3,
              max: 12,
              step: 1,
              marks: { 3: "3", 7: "7", 12: "12" },
            },
            {
              key: "fanLyricsLineHeight",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsLineHeight" },
              defaultValue: 96,
              min: 32,
              max: 140,
              step: 2,
              marks: { 32: "32", 96: "96", 140: "140" },
            },
            {
              key: "fanLyricsMinScale",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMinScale" },
              defaultValue: 0.78,
              min: 0.3,
              max: 1,
              step: 0.02,
              marks: { 0.3: "0.3", 0.78: "0.78", 1: "1" },
            },
            {
              key: "fanLyricsMinOpacity",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMinOpacity" },
              defaultValue: 0,
              min: 0,
              max: 1,
              step: 0.05,
              marks: { 0: "0", 0.3: "0.3", 1: "1" },
            },
            {
              key: "fanLyricsMaxBlur",
              type: "slider",
              binding: { store: "settings", path: "player.fanLyricsMaxBlur" },
              defaultValue: 7,
              min: 0,
              max: 8,
              step: 0.5,
              marks: { 0: "0", 4: "4", 8: "8" },
            },
            {
              key: "fanLyricsEnableBackground",
              type: "switch",
              binding: { store: "settings", path: "player.fanLyricsEnableBackground" },
              defaultValue: true,
            },
            {
              key: "fanLyricsEnableGlow",
              type: "switch",
              binding: { store: "settings", path: "player.fanLyricsEnableGlow" },
              defaultValue: true,
            },
          ],
        },
      ],
    },
    {
      id: "musicSpectrum",
      tag: { text: "Beta" },
      items: [
        {
          key: "enableSpectrum",
          type: "switch",
          binding: { store: "settings", path: "player.enableSpectrum" },
          defaultValue: false,
          children: [
            {
              key: "spectrumBarWidth",
              type: "slider",
              binding: { store: "settings", path: "player.spectrumBarWidth" },
              min: 1,
              max: 12,
              step: 1,
              defaultValue: 4,
              marks: { 1: "1", 4: "4", 8: "8", 12: "12" },
            },
            {
              key: "spectrumSensitivity",
              type: "slider",
              binding: { store: "settings", path: "player.spectrumSensitivity" },
              min: 0.5,
              max: 3,
              step: 0.1,
              defaultValue: 1,
              marks: { 0.5: "0.5", 1: "1", 2: "2", 3: "3" },
            },
            {
              key: "spectrumMaxHeight",
              type: "slider",
              binding: { store: "settings", path: "player.spectrumMaxHeight" },
              min: 0.3,
              max: 1,
              step: 0.05,
              defaultValue: 1,
              marks: { 0.3: "0.3", 0.7: "0.7", 1: "1" },
            },
            {
              key: "spectrumSmoothing",
              type: "slider",
              binding: { store: "settings", path: "player.spectrumSmoothing" },
              min: 0,
              max: 0.9,
              step: 0.05,
              defaultValue: 0.5,
              marks: { 0: "0", 0.5: "0.5", 0.9: "0.9" },
            },
          ],
        },
      ],
    },

    {
      id: "device",
      items: [
        {
          key: "outputDevice",
          type: "custom",
          component: DeviceSelector,
        },
        {
          key: "pauseOnDeviceSwitch",
          type: "switch",
          binding: { store: "settings", path: "player.pauseOnDeviceSwitch" },
          defaultValue: false,
        },
      ],
    },
  ],
};

export default playerCategory;
