/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class ThumbnailService {
  constructor(hwndBuffer: Buffer)
  /** 用 TypeScript 预缩放的 BGRA buckets 原子替换全部 DIB，WndProc 不再缩放或分配。 */
  setCoverVariants(variants: Array<JsBitmapVariant>): void
  /** 恢复系统默认窗口预览。重复调用无害。 */
  disable(): void
}

export interface JsBitmapVariant {
  bgra: Buffer
  width: number
  height: number
}
