/* auto-generated by NAPI-RS */
/* eslint-disable */
export declare class RegistryWatcher {
  /**
   * 监听 HKCU 下指定子键变化；`sub_key` 用反斜杠分隔，如
   * `Software\\Microsoft\\Windows\\CurrentVersion\\Explorer\\Advanced`
   */
  constructor(subKey: string, callback: () => void)
  stop(): void
}

export declare class TaskbarCreatedWatcher {
  constructor(callback: () => void)
  stop(): void
}
export type NapiTaskbarCreatedWatcher = TaskbarCreatedWatcher

export declare class TaskbarService {
  constructor(callback: (layout: JsTaskbarLayout) => void)
  /** 嵌入窗口到任务栏。传入 Electron BrowserWindow 的 native handle (Buffer → usize) */
  embedWindowByPtr(hwndPtr: number): void
  /** 更新歌词显示宽度，触发重新计算布局 */
  update(lyricWidth: number): void
  /** 通知服务重建策略（explorer.exe 重启时由 JS 层调用） */
  reinit(): void
  /** 停止服务并恢复任务栏原始状态 */
  stop(): void
}

export declare class TrayWatcher {
  constructor(callback: () => void)
  stop(): void
}
export type NapiTrayWatcher = TrayWatcher

export declare class UiaWatcher {
  constructor(callback: () => void)
  stop(): void
}
export type NapiUiaWatcher = UiaWatcher

export interface JsAvailableSpace {
  left: JsRect
  right: JsRect
}

/** 窗口的嵌入状态 */
export interface JsEmbedState {
  /** HWND 是否仍然有效 */
  alive: boolean
  /** 是否仍嵌在 explorer 的任务栏上 */
  embedded: boolean
}

export interface JsExtraLayoutInfo {
  /** "win10" | "win11" */
  systemType: string
  isCentered: boolean
  /** 任务栏是否为浅色主题 */
  isLight: boolean
}

export interface JsRect {
  x: number
  y: number
  width: number
  height: number
}

export interface JsTaskbarLayout {
  space: JsAvailableSpace
  extra: JsExtraLayoutInfo
}

/**
 * 探测窗口是否仍挂在 explorer 的任务栏上
 *
 * 任务栏歌词窗口的位置坐标是「相对任务栏」的（y=0 即任务栏顶边），父关系一旦被解除，
 * 同一组坐标会被按屏幕坐标解释，窗口就停在屏幕顶部且不会自行恢复
 * @param hwnd_ptr - Electron BrowserWindow 的 native handle
 * @returns 窗口是否存活、是否仍嵌在任务栏上
 */
export declare function probeWindow(hwndPtr: number): JsEmbedState
