/* auto-generated by NAPI-RS */
/* eslint-disable */
/** 通过 portal 绑定全部全局快捷键（重绑会先释放旧会话） */
export declare function bindShortcuts(shortcuts: Array<PortalShortcut>): Promise<PortalResult>

/** 打开系统侧快捷键配置界面（需 portal version >= 2） */
export declare function configureShortcuts(): Promise<PortalResult>

/** 检测 portal 后端是否支持 GlobalShortcuts 接口 */
export declare function detect(): Promise<PortalCapability>

/** 初始化原生日志系统（主进程启动时调用一次） */
export declare function initLogger(logDir: string, isDev: boolean): void

/** 注册激活回调，portal 触发快捷键时回调对应动作 id */
export declare function onActivated(callback: ((err: Error | null, arg: string) => any)): void

/** portal 后端能力探测结果 */
export interface PortalCapability {
  /** 是否支持 GlobalShortcuts 接口 */
  supported: boolean
  /** portal 接口版本 */
  version: number
  /** 是否支持 ConfigureShortcuts（version >= 2） */
  configureSupported: boolean
  /** 探测失败时的错误信息 */
  error?: string
}

/** portal 操作结果 */
export interface PortalResult {
  ok: boolean
  error?: string
}

/** 单个要绑定到 portal 的全局快捷键 */
export interface PortalShortcut {
  /** 固定动作 id（与 Electron 侧 HotkeyActionId 一致） */
  id: string
  /** 本地化描述（labelKey 对应的文本） */
  description: string
  /** preferred_trigger（XDG shortcuts 规范语法，如 "CTRL+SHIFT+space"） */
  preferredTrigger?: string
}

/** 关闭并清理资源（应用退出时调用，fire-and-forget 即可） */
export declare function shutdown(): Promise<void>

/** 释放当前 portal 会话（解绑全部快捷键） */
export declare function unbindShortcuts(): Promise<PortalResult>
